import { resolveJSONSchema, generateJoi, formatJoi } from './joi';
import { JSONSchema4 } from 'json-schema';

const schemas: JSONSchema4[] = [
  {
    '$schema': 'http://json-schema.org/schema#', 
    'required': [
      'device_id', 
      'owner_id', 
      'original_owner_id', 
      'imsi', 
      'msisdn'
    ], 
    'type': 'object', 
    'properties': {
      'original_owner_id': {
        'type': 'string', 
        'example': 'mts-194165',
        'default': 'mts-194165',
      }, 
      'msisdn': {
        'type': 'string', 
        'example': '601017519416601'
      }, 
      'vimsi': {
        'type': 'string', 
        'example': '12345678907777'
      }, 
      'owner_id': {
        'type': 'string', 
        'example': 'mts-194166'
      }, 
      'imsi': {
        'type': 'string', 
        'example': '401017519416601'
      }, 
      'device_id': {
        'type': 'string', 
        'description': 'Unique device identifier generated by the device.', 
        'example': 'mts-194166-amazon'
      }
    }, 
    'title': 'vowifiActivation'
  },
  {
    '$schema': 'http://json-schema.org/schema#', 
    'required': [
      'service_instance_id'
    ], 
    'type': 'object', 
    'properties': {
      'reason': {
        'enum': [
          0, 
          1, 
          2, 
          3, 
          4, 
          5, 
          6, 
          7, 
          8, 
          9, 
          10, 
          11, 
          12, 
          13, 
          14, 
          99, 
          100
        ], 
        'type': 'integer'
      }, 
      'service_instance_id': {
        'type': 'string', 
        'example': 'SESc974cae802e8bfc71b9b7b040e6a87f2'
      }
    }, 
    'title': 'vowifiDeactivation'
  }
];

schemas.forEach((schema) => {
  const joiSchema = resolveJSONSchema(schema);
  // console.dir(joiSchema, {
  //   depth: 1000,
  //   maxArrayLength:1000,
  // });
  const joiString = generateJoi(joiSchema);
  // console.log(joiString.toString());
  console.log(formatJoi(joiString));
});
